### ISSUE TITLE
enhancement: Config option to control each level of compress

### ISSUE THREAD

**Issue by MadRatSRP** [Sediments/Compressions#2]
> The second one is something I'm definitely going to do. Just like how you can now control the level of compression, you're gonna have a variable in the config file to control the size of compression. It's gonna be between 2 and 9. And eventually I'll add support for per item setting, like for example, you can have sand be 2x and 4 grid, and cobblestone be 4x and 9 grid. Hmm, maybe I'll name it like 3x4 (for the 3 levels of compression of 4 per pack), 4x9 (4 level, 9 grid).

**Comment by Sediments** [comment]
I've decided to add this in the current rewrite. This and individual control of options on a per item basis. Basically I'm completely rewriting how the config file works. Expect it in a couple of days.

**Comment by Sediments** [comment]
Implemented in the new version.
