### ISSUE TITLE
enhancement:Compressed blocks of modded items

### ISSUE THREAD

**Issue by MadRatSRP** [Sediments/Compressions#3]
While non-modded compressed blocks have they own textures, modded compressed items should use texture of non-compressed modded item.

**Comment by Sediments** [comment]
Do you mean compressed items from like extra utils? I was thinking of perhaps chaining in that case, like that mod adds a fixed amount of levels of compression, if a person defines something extra in the config file then I would add it to that existing compressed implementation, like extra levels, or compressed recipes. And the textures used in chaining would be of that compressed implementation continued.

Or are you talking about something else like how iron bars have a compressed block by default, I shouldn't use that one but the one of the iron bar?

Or are you talking about something else entirely? Give me an example, I'm not really getting it.

**Comment by MadRatSRP** [comment]
Here is what i mean. For example,  block of copper. It has its own textures. For each compressed version of it i want the same texture as copper block. And the same rules for others modded things.

**Comment by Sediments** [comment]
I implemented this (in the settings config file). It that what you wanted?
